- name: Deploy portfolio to EC2
  hosts: webserver
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Copy portfolio app in Dockerfile to EC2
      copy:
        src: ../portfolio/
        dest: /home/ubuntu/portfolio/
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Build Docker image
      command: docker build -t portfolio-site .
      args:
        chdir: /home/ubuntu/portfolio/

    - name: Run Docker container
      command: docker run -d -p 80:80 --name portfolio-container portfolio-site
