- name: Deploy portfolio to EC2
  hosts: webserver
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull portfolio image from Docker Hub
      command: docker pull gurpreet1999/portfolio-site:latest

    - name: Run Docker container
      command: docker run -d -p 80:80 --name portfolio-container --rm gurpreet1999/portfolio-site:latest
      args:
        warn: false
     
