trigger: none 

parameters:
  - name: ec2_ip
    displayName: 'EC2 IP Address'
    type: string
    default: ''

  - name: environment
    displayName: 'Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - staging
      - prod

stages:
- stage: AnsibleDeploy
  displayName: 'Deploy with Ansible'
  jobs:
    - deployment: DeployWithAnsible
      displayName: 'Deploy on EC2 with Ansible'
      environment: ${{ parameters.environment }}  
      pool:
        name: mypool  
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              - task: DownloadSecureFile@1
                name: fetchPem
                inputs:
                  secureFile: 'ok.pem'  

              - script: |
                  echo "Deploying to EC2 IP: ${{ parameters.ec2_ip }}"
                  cp $(fetchPem.secureFilePath) ansible/ok.pem
                  chmod 600 ansible/ok.pem
                  cd ansible
                  ansible-playbook deploy.yml -i "${{ parameters.ec2_ip }}," -u ubuntu --private-key ok.pem
                displayName: 'Run Ansible Playbook'
