parameters:
  - name: environment
    displayName: 'Select environment'
    type: string
    default: 'dev'
    values:
      - dev
      - staging
      - prod

trigger: none 

stages:
- stage: Terraform
  displayName: 'Provision Infrastructure'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    pool:
      name: mypool 
    steps:
    - checkout: self



    - script: |
        echo "Selected environment: ${{ parameters.environment }}"
        cd terraform

        terraform init

        terraform workspace select ${{ parameters.environment }} || terraform workspace new ${{ parameters.environment }}

        terraform apply -auto-approve 

        terraform output -json > output.json
      displayName: 'Terraform Init, Plan, Apply'

    - publish: terraform/output.json
      artifact: terraformOutput
